### ISSUE TITLE
Prefooter: Find out more button isn't aligned with Contact us now button.  It should display if button label is empty in the first place.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Interfreight-Logistics#105]
![image](https://cloud.githubusercontent.com/assets/11186313/14911997/dacf70f0-0e2b-11e6-8906-2478fd1f175f.png)

**Comment by nakul-titan** [comment]
it is aligned and working fine in all browsers

**Comment by roseliesromeo** [comment]
It's not when its empty
