### ISSUE TITLE
Lead-ins: ACF for lead-in section title and content are not implemented

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#12]
![image](https://cloud.githubusercontent.com/assets/12888048/14488094/0adc5e9c-0199-11e6-939e-8870c01fc07f.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14488113/18a0b50a-0199-11e6-9163-9ecaa24bc42b.png)

**Comment by nakul-titan** [comment]
Hi
It is implemented.
![leadins title](https://cloud.githubusercontent.com/assets/13461911/14599676/53c6222e-0576-11e6-8ec0-5d8d20181b6b.png)
