### ISSUE TITLE
Pre Footer: Text "INTERFREIGHT LOGISTICS" above the business text seems to be hard coded

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#17]
![image](https://cloud.githubusercontent.com/assets/12888048/14513870/fb2c36ae-021d-11e6-9aa4-2835f3a59ad6.png)

**Comment by nakul-titan** [comment]
Hi
It is Coming from the site title.
![prefooter title](https://cloud.githubusercontent.com/assets/13461911/14599721/9cea83c8-0576-11e6-9791-045a57e14cb3.png)
