### ISSUE TITLE
Titan Theme Options: Create Tab options

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#20]
![image](https://cloud.githubusercontent.com/assets/12888048/14514416/10c563fa-0223-11e6-8448-903421f64502.png)

**Comment by ricatitan** [comment]
Lacking tab options.
![image](https://cloud.githubusercontent.com/assets/18568310/14812322/4c37bedc-0bcf-11e6-92aa-06324136e1df.png)
