### ISSUE TITLE
Media: Never use images with watermark!

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#23]
Reference: https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/using-images

![image](https://cloud.githubusercontent.com/assets/12888048/14515817/d7861b72-022f-11e6-9c21-603e90e06948.png)

**Comment by ricatitan** [comment]
There are still images with watermark
![image](https://cloud.githubusercontent.com/assets/18568310/14811406/8ed281d2-0bca-11e6-834a-8579448a5f18.png)
