### ISSUE TITLE
Homepage - Why Choose: No padding or margin between items

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#28]
![image](https://cloud.githubusercontent.com/assets/12888048/14516674/1567c316-0238-11e6-9633-82177f2036a4.png)

**Comment by ricatitan** [comment]
No padding or margin between items 
![image](https://cloud.githubusercontent.com/assets/18568310/14810692/c25dc3d0-0bc6-11e6-8289-e54885245b8e.png)
