### ISSUE TITLE
Homepage: div for News and Testimonial content should be aligned. It should have a fix height.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#30]
![image](https://cloud.githubusercontent.com/assets/12888048/14518118/57d338b6-0247-11e6-99f4-0169a3dc7443.png)

**Comment by ricatitan** [comment]
Still not aligned
![image](https://cloud.githubusercontent.com/assets/18568310/14810430/86d2788e-0bc5-11e6-97eb-e97e0b54534c.png)
