### ISSUE TITLE
Homepage - Leadins: Blank repeater was displayed in front end

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#34]
![image](https://cloud.githubusercontent.com/assets/12888048/14519111/53e3ed6a-024f-11e6-89f5-d2129edc70c9.png)

**Comment by ricatitan** [comment]
Blank repeater was displayed in front end 
![image](https://cloud.githubusercontent.com/assets/18568310/14809912/c8053420-0bc2-11e6-96d1-84ef3b22ea8b.png)
