### ISSUE TITLE
Homepage - Leadins: All lead-ins should be align

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#36]
![image](https://cloud.githubusercontent.com/assets/12888048/14519210/004f9982-0250-11e6-8e69-c3a6d551dbbb.png)

**Comment by ricatitan** [comment]
Error still occurs
![image](https://cloud.githubusercontent.com/assets/18568310/14809817/1fe721fe-0bc2-11e6-81f8-7d5d4306758b.png)
