### ISSUE TITLE
Homepage - Lead-ins: Space between the last 2 lead-ins is larger compared to others

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#37]
Padding/Margin between lead-ins should be equal to **30px**

![image](https://cloud.githubusercontent.com/assets/12888048/14519937/6305ce26-0254-11e6-8302-7d114c7c30ac.png)

**Comment by ricatitan** [comment]
Space between the last 2 lead-ins is larger compared to others. No changes made
![image](https://cloud.githubusercontent.com/assets/18568310/14840056/fa56c1aa-0c62-11e6-9a76-2f7b0ff3547a.png)

**Comment by roseliesromeo** [comment]
Left side of the lead-in section has no padding while right has.  Please implement as per design.
![image](https://cloud.githubusercontent.com/assets/11186313/14907686/e9ad55f6-0dfe-11e6-94bb-fc2a9110c533.png)
