### ISSUE TITLE
Banner did not pause on hover. It should pause when the mouse hover on it.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#40]

**Comment by nakul-titan** [comment]
Hi
"asNavFor" will not work for two sliders, as they are two scripts running one for the content and another for the image.

**Comment by ricatitan** [comment]
Banner should pause when mouse hover on it because it has text 
http://kenwheeler.github.io/slick/

**Comment by nakul-titan** [comment]
Since there are two scripts working, it will work for only one script either content or image
