### ISSUE TITLE
Pre - Footer: An additional "Find Out More" button should be added alongside the Contact Us Now button.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#43]
![image](https://cloud.githubusercontent.com/assets/12888048/14521672/0822cc58-025d-11e6-96be-e80accd60eea.png)

**Comment by ricatitan** [comment]
No changes made.

![image](https://cloud.githubusercontent.com/assets/18568310/14808313/e1bb5004-0bb6-11e6-8349-00011248c3c7.png)
