### ISSUE TITLE
Homepage: W3C Error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#44]
![image](https://cloud.githubusercontent.com/assets/12888048/14521749/88684b2c-025d-11e6-82e5-55c0fd9579c7.png)

**Comment by ricatitan** [comment]
Still W3C Error
![image](https://cloud.githubusercontent.com/assets/18568310/14808250/52e4f04c-0bb6-11e6-88f8-c0ec8cc51905.png)
