### ISSUE TITLE
General: Page element should be aligned properly inside the 1140px bootstrap grid layout

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#45]
Notes:
**There should be a gutter, left(15px) and right(15px) equals to 30px.
1140px bootstrap grid + 30px gutter = 1170px**

Affected pages:
Homepage
Contact Us Page

![image](https://cloud.githubusercontent.com/assets/12888048/14521776/a77bb3a0-025d-11e6-8ea4-df1d0bb31eb0.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14521779/aa07b1e6-025d-11e6-99f9-0ec118b42ec3.png)

**Comment by ricatitan** [comment]
Error still occurs. Page elements are still not aligned properly inside the 1140px bootstrap grid layout
![image](https://cloud.githubusercontent.com/assets/18568310/14839393/1e4b7354-0c5d-11e6-9c7a-ed62423de5bf.png)

**Comment by roseliesromeo** [comment]
Header section is beyond the 1140px.
