### ISSUE TITLE
Header: All child sub menus appears after hovering on parent sub menu

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#46]
Step to Replicate:
1. Hover on the "About Us" main menu
2. Hover on "Sitemap" sub menu
3. Observe that all sub menus appears after hovering on its parent sub-menu

![image](https://cloud.githubusercontent.com/assets/12888048/14521989/fbbae0f2-025e-11e6-9966-2769376ff902.png)

**Comment by ricatitan** [comment]
Please refer to bug #97
