### ISSUE TITLE
Quote Form: Datepicker

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#5]
Datepicker "Prev" and "Next" should be separated
![image](https://cloud.githubusercontent.com/assets/12888048/14486476/ba3275ca-018f-11e6-82cf-111e239fd712.png)

Align the Month and Year to center
![image](https://cloud.githubusercontent.com/assets/12888048/14486511/e5722262-018f-11e6-86f8-4a2e23bf2b58.png)

**Comment by ricatitan** [comment]
Month and Year are still not align in the center

![image](https://cloud.githubusercontent.com/assets/18568310/14839061/0839f642-0c5a-11e6-9b3b-ed7c5dc38d3d.png)
