### ISSUE TITLE
News: Font awesome arrow was cut

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#64]
![image](https://cloud.githubusercontent.com/assets/12888048/14548606/e2f435fa-02ea-11e6-88b2-81280ef67832.png)

**Comment by ricatitan** [comment]
Error still occur
![image](https://cloud.githubusercontent.com/assets/18568310/14806359/d6777504-0ba4-11e6-960b-20b9c2e01785.png)

**Comment by nakul-titan** [comment]
Due to small font font size arrow is appearing like that, it is directly coming from the fontawesome, ou can increase the size and check
