### ISSUE TITLE
News: The Load More button disappears after the first load. The unable to display the remaining posts because the button was already hidden.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#69]
There is total of 12 posts in News category
4 posts displayed by default
4 posts were displayed after clicking the "Load More" button.
The "Load More" button disappear after the first load.
The unable to display the remaining posts because the button was already hidden.

![image](https://cloud.githubusercontent.com/assets/12888048/14548858/766a5308-02ed-11e6-9795-07570d4c6ef7.png)

![news 01](https://cloud.githubusercontent.com/assets/12888048/14548871/85b1f014-02ed-11e6-85ec-a099eda8d3c0.jpg)

**Comment by ricatitan** [comment]
Error is still existing. The Load More button disappears after the first load
