### ISSUE TITLE
Contact Us: There should be enough margin between fields

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#80]
![image](https://cloud.githubusercontent.com/assets/12888048/14549605/d123b27a-02f3-11e6-96fa-d358cb9bddfe.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14549608/d3594dde-02f3-11e6-896a-bc1a3304cbb7.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14549609/d4fe0fb2-02f3-11e6-83e3-1b87d3d1b144.png)

**Comment by ricatitan** [comment]
Same error still occurs

**Comment by nakul-titan** [comment]
It is 18px only
![contact](https://cloud.githubusercontent.com/assets/13461911/14877068/c3797d82-0d37-11e6-8d84-e0991bcef5a8.png)
