### ISSUE TITLE
General: Incorrect page hyperlink text font color. It should be #da0808

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#85]
![image](https://cloud.githubusercontent.com/assets/12888048/14550247/a22df0c4-02f9-11e6-9390-f79711cc73d9.png)

**Comment by ricatitan** [comment]
Still incorrect page hyperlink text font color
![image](https://cloud.githubusercontent.com/assets/18568310/14804656/df68c292-0b97-11e6-8cb0-69c6c1526dd8.png)

**Comment by roseliesromeo** [comment]
Not fixed for hyperlinks in single pages.
http://interfreightlogistics.stage.titanweb.com.au/service/services-complete-title-goes-here-for-this-long-title-goes-here-for-this-long-title-goes-here-for-this-long-title-goes-here-for-this-long-title-goes-here-for-this-long/
