### ISSUE TITLE
Header: Responsive checking

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#86]
![header 01](https://cloud.githubusercontent.com/assets/12888048/14552439/0f8de7de-0311-11e6-85ea-4b4143376984.jpg)

**Comment by ricatitan** [comment]
Still not align well 
![image](https://cloud.githubusercontent.com/assets/18568310/14804528/dbe2581e-0b96-11e6-899b-d297f8b2c1cf.png)
