### ISSUE TITLE
Testimonials: Responsive Errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#89]
![image](https://cloud.githubusercontent.com/assets/12888048/14552472/54ce4230-0311-11e6-88e9-b91f1a5d459e.png)
![image](https://cloud.githubusercontent.com/assets/12888048/14552478/69eaee70-0311-11e6-848b-834bc34a9f4c.png)

**Comment by ricatitan** [comment]
Error still occurs
![image](https://cloud.githubusercontent.com/assets/18568310/14809066/1013e5c8-0bbd-11e6-9331-91130560ef48.png)
