### ISSUE TITLE
Homepage - Why Choose/News/Testimonials section: Responsive errors

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Interfreight-Logistics#90]
![image](https://cloud.githubusercontent.com/assets/12888048/14552527/e657e2c4-0311-11e6-87fd-1361749aca6c.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14552528/e845437e-0311-11e6-8621-95c7ff09eac7.png)

![image](https://cloud.githubusercontent.com/assets/12888048/14552574/4eec0ac2-0312-11e6-9192-963e2db77148.png)

**Comment by nakul-titan** [comment]
Hi,
As per the scope title is restricted to one line only
